### ISSUE TITLE
Request for small improvements

### ISSUE THREAD

**Issue by ahlinc** [camdencheek/tree-sitter-dockerfile#1]
Hi :wave: 
_Awesome work! It's great that tree-sitter would have one another parser!_

I would like to suggest to change indentation in `grammar.js` from tabs to spaces to make in easily readable even on Github interface, cause now it looks scattered https://github.com/camdencheek/tree-sitter-dockerfile/blob/main/grammar.js

And also it would be good to see explicitly specified licence for this repo.
Just for the note, most tree-sitter languages authors choose MIT, the same as tree-sitter itself.

**Comment by camdencheek** [comment]
Hey -- thanks for the suggestions! 

I've formatted `grammar.js` with `prettier` in f3a88aa6869, and added the MIT license in b25f86c3b2ec4192d040432a1a279861df390762. Feel free to reach out with any other improvements! I'm new to tree-sitter, so am definitely still working on figuring out best practices.
