### ISSUE TITLE
Parser errors on comment immediately after RUN

### ISSUE THREAD

**Issue by thetic** [camdencheek/tree-sitter-dockerfile#10]
The following causes an error:

```dockerfile
RUN \
  # comment
  echo foo
```

Whereas none of the following do:

```dockerfile
RUN echo foo \
  # comment
  echo foo
```

```dockerfile
# comment
RUN \
  echo foo
```

```dockerfile
RUN \
  echo foo \
  # comment
  echo foo
```

**Comment by camdencheek** [comment]
Thanks for the report! I just pushed [a commit](https://github.com/camdencheek/tree-sitter-dockerfile/commit/28ac8596bab00b2dac9a76deaa9c4cb2b22642fd) to `main` that should fix this issue.

**Comment by thetic** [comment]
I just noticed that this also affects `ENV`:

```dockerfile
ENV \
   # comment
  VAR=value
```

**Comment by camdencheek** [comment]
Sure enough. Thanks for the vigilance 😄 

I'll reopen this until I get to fixing the issue for all commands.

**Comment by vcunat** [comment]
I see issue e.g. on:
```dockerfile
FROM image
ENV FOO bar baz
ENV BAR foo
```
with the last `ENV` not getting highlighted.  Similarly to this, "multi-parameter" `EXPOSE` also does this.

**Comment by camdencheek** [comment]
Okay, the issue with comment lines not being removed after line continuations should be fixed by https://github.com/camdencheek/tree-sitter-dockerfile/commit/439c3e7b8a9bfdbf1f7d7c2beaae4173dc484cbf. Thanks for the report!
