### ISSUE TITLE
Parse Error with Port Range

### ISSUE THREAD

**Issue by CKolkey** [camdencheek/tree-sitter-dockerfile#27]
There seems to be a parsing error here:
![Screenshot 2022-10-20 at 12 58 19](https://user-images.githubusercontent.com/7228095/196930862-a8a773a3-2608-490c-989e-47d08597a5a5.png)

And the corresponding treesitter-playground buffer:
![Screenshot 2022-10-20 at 12 58 47](https://user-images.githubusercontent.com/7228095/196930967-6aecd699-c386-4e0e-b167-bab9af7bf534.png)

**Comment by camdencheek** [comment]
Thanks for the report! Fixed in https://github.com/camdencheek/tree-sitter-dockerfile/commit/ecea7ac2c935de590d2ea091a90c6160237654f9
