### ISSUE TITLE
Rename to `containerfile` 

### ISSUE THREAD

**Issue by dzintars** [camdencheek/tree-sitter-dockerfile#33]
Name "dockerfile" is kind of tied to one specific vendor.
I suggest to rename it to `tree-sitter-containerfile`.
Not sure about really deep details, but it should work out of the box without any other modifications.

**Comment by mjambon** [comment]
Well, "dockerfile" here is the name of the format, not the name of a file.

I strongly believe that whoever created the format and maintains the reference material should get to name it. Until the format evolves significantly beyond what Docker supports or Docker decides to rename it, I would stick with "dockerfile" to refer to the language.

**Comment by camdencheek** [comment]
This grammar was built specifically to support Dockerfile syntax, which _is_ vendor-specific. It will likely work out-of-the-box for Containerfiles as you mentioned, but that is not a specific goal of this grammar, and if the formats ever diverge, this grammar will prefer supporting whatever Dockerfile does. For that reason, I think it's appropriate to leave the name as is, and in the event that we need two grammars (or Containerfile becomes dominant and the repo name matters), we can fork this into `tree-sitter-containerfile`.
