### ISSUE TITLE
Heredoc support?

### ISSUE THREAD

**Issue by neezer** [camdencheek/tree-sitter-dockerfile#4]
Hi! Awesome work with this!

I know it's relatively hot-off-the-press, but could we get [Docker Heredoc](https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/) support?

**Comment by camdencheek** [comment]
Thanks for pointing that out! I saw heredocs were released, but forgot to ever follow up on it with the grammar.

I'll need to do a bit more looking into this. Basically, I think heredocs will break some assumptions the grammar currently has about command endings and what we can delegate to the nested shell grammar. If we can't delegate heredocs to the shell grammar, this will almost certainly require making an external scanner in C. I'm not particularly familiar with C, so this might be a longer-than-seemingly-necessary process, but I'll see what I can do 😄

**Comment by mmetc** [comment]
Hi, was there any progress on this?

If it's simpler, support for "COPY <<eot" with embedded files would be useful enough. No need for fancy grammars inside the doc

thanks

**Comment by smason** [comment]
I'm also interested in know what happened to this!

I've written quite a bit of C code in my time, so could help out if you point me in the right direction.  I've never done much with tree-sitter so don't know where to get started.

**Comment by camdencheek** [comment]
Thanks to @tvrinssen, this long-standing gap has finally been fixed in #45!

**Comment by danihodovic** [comment]
Awesome!
