### ISSUE TITLE
Tolerate blanks in line continuations after the backslash

### ISSUE THREAD

**Issue by mjambon** [camdencheek/tree-sitter-dockerfile#50]
This was reported here: https://github.com/semgrep/semgrep/issues/9539

A dockerfile like the following is tolerated by `docker` but not by tree-sitter-dockerfile:
```
FROM ubuntu

# blanks (spaces or tabs) after the backslash:
RUN \      	
echo hello
```

I don't see it documented at https://docs.docker.com/reference/dockerfile/#format
It is unusual for users to expect this to work but it happens by accident and their dockerfiles work as intended, so we may have to support it.

**Comment by camdencheek** [comment]
I think I [just fixed this](https://github.com/camdencheek/tree-sitter-dockerfile/commit/40eceeff3051f17cc02bcfa84baa6a51b35d5776) actually. Will get a release out as soon as I can

**Comment by mjambon** [comment]
Fantastic. Thank you!

**Comment by camdencheek** [comment]
Should be good to go in v0.2.0. Thanks for the report!
